server:
  port: 7001

spring:
  application:
    name: mq-test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: ryl123

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: ryl123
    publisher-confirm-type: correlated
    listener.simple.acknowledge-mode: manual

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

mq.env: dev
mq.order.dead.exchange.name: ${mq.env}.middleware.dead.exchange
mq.order.dead.routing.key.name: ${mq.env}.middleware.dead.routing.key
mq.order.dead.queue.name: ${mq.env}.middleware.dead.queue
mq.order.producer.exchange.name: ${mq.env}.middleware.producer.basic.exchange
mq.order.producer.routing.key.name: ${mq.env}.middleware.producer.basic.routing.key
mq.order.real.queue.name: ${mq.env}.middleware.consumer.real.queue

